
# compilação dos testes unitários:

deque-ligada:
	gcc -I .. -D_UT_DEQUE_LIGADA -o ut_dequeligada dequeligada.c \
	../aleatorio.c ../teste.c ../terminal.c ../legivel.c ../tempo.c \
	-Wall -lm -Wno-unused-function
